version: '3'
services:
  web:
    image: golang:latest
    build: api
    ports:
      - "8080:8080"
    links:
      - "db"
    volumes:
      - "./api:/go/src/hit_u_bad"
    tty: true
  db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - "./database:/var/lib/postgresql/data"