backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "[netlify-cms] Create {{slug}}"
    update: "[netlify-cms] Update {{slug}}"
    delete: "[netlify-cms] Delete {{slug}}"
    uploadMedia: "[netlify-cms] Upload file '{{path}}'"
    deleteMedia: "[netlify-cms] Delete file '{{path}}'"
media_folder: static/files
public_folder: /files
collections:
  - name: "common"
    label: "ページ"
    folder: "markdown"
    create: true
    delete: true
    sortableFields: ["pageId", "title"]
    identifier_field: pageId
    fields:
      - { label: "ページ ID", name: "pageId", widget: "string" }
      - { label: "URL パス", name: "path", widget: "string" }
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown", required: false }
