backend:
  name: git-gateway
  branch: master
media_folder: static/files
public_folder: /img
collections:
  - name: "common"
    label: "固定ページ"
    folder: "markdown"
    create: false
    delete: false
    sortableFields: ["title"]
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "コンテンツ", name: "content", widget: "code", default_language: "json", allow_language_selection: false, output_code_only: true, required: false }
      - { label: "本文", name: "body", widget: "markdown", required: false }
