name: Deploy
on:
  push:
    branches:
      - release
  workflow_dispatch:
    branches:
      - release
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: install
        run: |
          yarn install
          yarn global add firebase-tools
          echo $(yarn global bin) >> $GITHUB_PATH
      - name: build
        run: |
          yarn run build
      - name: Deploy
        run: |
          firebase deploy --only hosting --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
